// COPYRIGHT JULIAN DANS AND STUFF
import Head from 'next/head'
import { Container, Text, Tabs, Tab, TabList, TabPanels, TabPanel, Center, IconButton } from '@chakra-ui/react' 
import { Auton, Game, Teleop, Teams, Review } from '../components/exportScreens'
import { useState, useRef } from 'react'
import { ColorModeSwitcher } from '../components/ColorModeSwitcher'
import { FaArrowRight } from 'react-icons/fa'
import { cowsay } from 'cowsayjs'
// import chalk from 'chalk'

console.log(
  cowsay('I\'m the robotics cow!')

)

export default function Home() {
  const [team, setTeam] = useState();
  const [match, setMatch] = useState();
  const [alliance, setAlliance] = useState();
  const [zone, setZone] = useState();
  const [ltc, setLtc] = useState();
  const [autonParking, setAutonParking] = useState();
  const [autonConesScoredLow, setAutonConesScoredLow] = useState(0);
  const [autonConesScoredMiddle, setAutonConesScoredMiddle] = useState(0);
  const [autonConesScoredHigh, setAutonConesScoredHigh] = useState(0);
  const [autonCubesScoredLow, setAutonCubesScoredLow] = useState(0);
  const [autonCubesScoredMiddle, setAutonCubesScoredMiddle] = useState(0);
  const [autonCubesScoredHigh, setAutonCubesScoredHigh] = useState(0);
  const [teleopConesScoredLow, setTeleopConesScoredLow] = useState(0);
  const [teleopConesScoredMiddle, setTeleopConesScoredMiddle] = useState(0);
  const [teleopConesScoredHigh, setTeleopConesScoredHigh] = useState(0);
  const [teleopCubesScoredLow, setTeleopCubesScoredLow] = useState(0);
  const [teleopCubesScoredMiddle, setTeleopCubesScoredMiddle] = useState(0);
  const [teleopCubesScoredHigh, setTeleopCubesScoredHigh] = useState(0);
  const [dropped, setDropped] = useState(0);
  const [failed, setFailed] = useState(0);
  const [outcome, setOutcome] = useState();
  const [speed, setSpeed] = useState();
  const [defenseRating, setDefenseRating] = useState();
  const [endgameParking, setEndgameParking] = useState();

  const teamsTab = useRef();
  const toTeams = () => { teamsTab.current.click() }
  const autonTab = useRef();
  const toAuton = () => { autonTab.current.click() }
  const gameTab = useRef();
  const toGame = () => { gameTab.current.click() }
  const teleopTab = useRef();
  const toTeleop = () => { teleopTab.current.click() }
  const reviewTab = useRef();
  const toReview = () => { reviewTab.current.click() }
//   const compositeTab = useRef();
//   const toComposite = () => { compositeTab.current.click() }


  const finalAnswer = { team, match, alliance, zone, ltc, autonParking, 
    autonConesScoredLow, autonConesScoredMiddle, autonConesScoredHigh, 
    autonCubesScoredLow, autonCubesScoredMiddle, autonCubesScoredHigh, 
    teleopConesScoredLow, teleopConesScoredMiddle, teleopConesScoredHigh, 
    teleopCubesScoredLow, teleopCubesScoredMiddle, teleopCubesScoredHigh, 
    dropped, failed, outcome, speed, defenseRating, endgameParking }

  return (
    <>
      <Head>
        <title>FRC Scouting App 2023</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <ColorModeSwitcher justifySelf="flex-end" marginTop="2" />
        <Center>
          <Container position="fixed" top="0" zIndex={1000}>
            <Center>
              <Text
                bgGradient='linear(to-l, #db5757, #473d3d)'
                bgClip='text'
                fontSize='7xl'
                fontWeight='extrabold'
              >
                FRC Scout
              </Text>
            </Center>
            <Tabs>
              <TabList>
                <Tab ref={teamsTab}>Teams</Tab>
                <Tab ref={autonTab}>Auton</Tab>
                <Tab ref={teleopTab}>Teleop</Tab>
                <Tab ref={gameTab}>Game</Tab>
                <Tab ref={reviewTab}>Review</Tab>
                {/* <Tab ref={compositeTab}>Composite</Tab> */}
              </TabList>
              <TabPanels>
                <TabPanel>
                  <Teams 
                    team={team} 
                    setTeam={setTeam}
                    match={match}
                    setMatch={setMatch}
                    alliance={alliance}
                    setAlliance={setAlliance}
                  />
                  <IconButton 
                    size="md"
                    fontSize="lg"
                    variant="ghost"
                    color="current"
                    icon={<FaArrowRight />}
                    onClick={toAuton}
                    marginLeft='100%'
                  />
                </TabPanel>
                <TabPanel>
                  <Auton 
                    alliance={alliance} 
                    zone={zone}
                    setZone={setZone}
                    ltc={ltc}
                    setLtc={setLtc}
                    autonParking={autonParking}
                    setAutonParking={setAutonParking}

                    autonCubesScoredLow={autonCubesScoredLow}
                    setAutonCubesScoredLow={setAutonCubesScoredLow}

                    autonCubesScoredMiddle={autonCubesScoredMiddle}
                    setAutonCubesScoredMiddle={setAutonCubesScoredMiddle}

                    autonCubesScoredHigh={autonCubesScoredHigh}
                    setAutonCubesScoredHigh={setAutonCubesScoredHigh}

                    autonConesScoredLow={autonConesScoredLow}
                    setAutonConesScoredLow={setAutonConesScoredLow}

                    autonConesScoredMiddle={autonConesScoredMiddle}
                    setAutonConesScoredMiddle={setAutonConesScoredMiddle}

                    autonConesScoredHigh={autonConesScoredHigh}
                    setAutonConesScoredHigh={setAutonConesScoredHigh}
                  />
                  <IconButton 
                    size="md"
                    fontSize="lg"
                    variant="ghost"
                    color="current"
                    icon={<FaArrowRight />}
                    onClick={toTeleop}
                    marginLeft='100%'
                  />
                </TabPanel>
                <TabPanel>
                  <Teleop
                    teleopCubesScoredLow={teleopCubesScoredLow}
                    setTeleopCubesScoredLow={setTeleopCubesScoredLow}

                    teleopCubesScoredMiddle={teleopCubesScoredMiddle}
                    setTeleopCubesScoredMiddle={setTeleopCubesScoredMiddle}

                    teleopCubesScoredHigh={teleopCubesScoredHigh}
                    setTeleopCubesScoredHigh={setTeleopCubesScoredHigh}

                    teleopConesScoredLow={teleopConesScoredLow}
                    setTeleopConesScoredLow={setTeleopConesScoredLow}

                    teleopConesScoredMiddle={teleopConesScoredMiddle}
                    setTeleopConesScoredMiddle={setTeleopConesScoredMiddle}

                    teleopConesScoredHigh={teleopConesScoredHigh}
                    setTeleopConesScoredHigh={setTeleopConesScoredHigh}

                    dropped={dropped}
                    setDropped={setDropped}

                    failed={failed}
                    setFailed={setFailed}

                    alliance={alliance}
                  />
                  <IconButton 
                    size="md"
                    fontSize="lg"
                    variant="ghost"
                    color="current"
                    icon={<FaArrowRight />}
                    onClick={toGame}
                    marginLeft='100%'
                  />
                </TabPanel>
                <TabPanel>
                  <Game 
                    outcome={outcome}
                    setOutcome={setOutcome}
                    speed={speed}
                    setSpeed={setSpeed}
                    defenseRating={defenseRating}
                    setDefenseRating={setDefenseRating}
                    endgameParking={endgameParking}
                    setEndgameParking={setEndgameParking}
                    alliance={alliance}
                  />
                  <IconButton 
                    size="md"
                    fontSize="lg"
                    variant="ghost"
                    color="current"
                    icon={<FaArrowRight />}
                    onClick={toReview}
                    marginLeft='100%'
                  />
                </TabPanel>
                <TabPanel>
                  <Review {...finalAnswer}/>
                </TabPanel>
                {/* <TabPanel>
                  <Composite />
                </TabPanel> */}
              </TabPanels>
            </Tabs>
          </Container>
        </Center>
      </div>
    </>
  )
}
