import Head from 'next/head'
import { Container, Text, Tabs, Tab, TabList, TabPanels, TabPanel, Center } from '@chakra-ui/react' 
import { Auton, Game, Score, Teams, Review } from '../components/exportScreens'
import { useState } from 'react'
import { ColorModeSwitcher } from '../components/ColorModeSwitcher'


export default function Home() {

  const [team, setTeam] = useState();
  const [match, setMatch] = useState();
  const [alliance, setAlliance] = useState();
  const [zone, setZone] = useState();
  const [ltc, setLtc] = useState();
  const [conesScoredLow, setConesScoredLow] = useState(0);
  const [conesScoredMiddle, setConesScoredMiddle] = useState(0);
  const [conesScoredHigh, setConesScoredHigh] = useState(0);
  const [cubesScoredLow, setCubesScoredLow] = useState(0);
  const [cubesScoredMiddle, setCubesScoredMiddle] = useState(0);
  const [cubesScoredHigh, setCubesScoredHigh] = useState(0);
  const [dropped, setDropped] = useState(0);
  const [failed, setFailed] = useState(0);
  const [outcome, setOutcome] = useState();
  const [speed, setSpeed] = useState();
  const [defenseRating, setDefenseRating] = useState();
  const [endgame, setEndgame] = useState();

  const finalAnswer = {team, match, alliance, zone, ltc, conesScoredLow, 
    conesScoredMiddle, conesScoredHigh, cubesScoredLow, cubesScoredMiddle, 
    cubesScoredHigh, dropped, failed, outcome, speed, defenseRating}

  return (
    <>
      <Head>
        <title>FRC Scouting App 2023</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ColorModeSwitcher justifySelf="flex-end" marginTop="2" />
      <Center>
        <Container position="fixed" top="0" zIndex={1000}>
          <Center>
            <Text
              bgGradient='linear(to-l, #db5757, #473d3d)'
              bgClip='text'
              fontSize='7xl'
              fontWeight='extrabold'
            >
              FRC Scout
            </Text>
          </Center>
          <Tabs>
            <TabList>
              <Tab>Teams</Tab>
              <Tab>Auton</Tab>
              <Tab>Score</Tab>
              <Tab>Game</Tab>
              <Tab>Review</Tab>
            </TabList>
            <TabPanels>
              <TabPanel>
                <Teams 
                  team={team} 
                  setTeam={setTeam}
                  match={match}
                  setMatch={setMatch}
                  alliance={alliance}
                  setAlliance={setAlliance}
                />
              </TabPanel>
              <TabPanel>
                <Auton 
                  alliance={alliance} 
                  zone={zone}
                  setZone={setZone}
                  ltc={ltc}
                  setLtc={setLtc}
                />
              </TabPanel>
              <TabPanel>
                <Score
                  cubesScoredLow={cubesScoredLow}
                  setCubesScoredLow={setCubesScoredLow}

                  cubesScoredMiddle={cubesScoredMiddle}
                  setCubesScoredMiddle={setCubesScoredMiddle}

                  cubesScoredHigh={cubesScoredHigh}
                  setCubesScoredHigh={setCubesScoredHigh}

                  conesScoredLow={conesScoredLow}
                  setConesScoredLow={setConesScoredLow}

                  conesScoredMiddle={conesScoredMiddle}
                  setConesScoredMiddle={setConesScoredMiddle}

                  conesScoredHigh={conesScoredHigh}
                  setConesScoredHigh={setConesScoredHigh}

                  dropped={dropped}
                  setDropped={setDropped}

                  failed={failed}
                  setFailed={setFailed}
                />
              </TabPanel>
              <TabPanel>
                <Game 
                  outcome={outcome}
                  setOutcome={setOutcome}
                  speed={speed}
                  setSpeed={setSpeed}
                  defenseRating={defenseRating}
                  setDefenseRating={setDefenseRating}
                  endgame={endgame}
                  setEndgame={setEndgame}
                />
              </TabPanel>
              <TabPanel>
                <Review {...finalAnswer}/>
              </TabPanel>
            </TabPanels>
          </Tabs>
        </Container>
      </Center>
    </>
  )
}
